bot :
  name: RecreationAssistantBot
  token: 5916701577:AAEDJ-y_aIjdhLyacaCfQwfqhVRYX8eINKY
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:/data/recreationAssistant
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
